update smart contract BridgeWrapToken, add withdraw fee mode
tomochain/tomoissuer pull request #203
Opened 2020-11-02 10:21 UTC by pqv199x

Add TOMO_FEE_MODE(bool) in order to take tomo as withdraw fee 
Add changeWithdrawFeeMode function in order to change TOMO_FEE_MODE
Set owner[0] as withdrawal fee receiver

2020-11-03 02:27 UTC, thanhson1085 requested changes

2020-11-03 02:27 UTC, thanhson1085 commented on contracts/TomoBridgeWrapToken.sol
> +            msg.sender.transfer(msg.value - WITHDRAW_FEE_TOMO);
Need to use safemath

2020-11-03 02:27 UTC, thanhson1085 commented on contracts/TomoBridgeWrapToken.sol
> +            emit TokenBurn(burnList.length - 1, msg.sender, burnValue, data);
There is No define for BurnValue?

2020-11-05 03:58 UTC, anhntbk08 requested changes

2020-11-05 04:36 UTC, anhntbk08 approved these changes

2020-11-05 04:42 UTC, thanhson1085 approved these changes

2020-11-05 07:02 UTC, merged